version: '3.9'

services:

  IOT-V2-Tdengine:
    image: tdengine/tdengine:latest
    container_name: tdengine
    ports:
      - "6030:6030"
      - "6041:6041"
      - "6043-6049:6043-6049"
      - "6043-6049:6043-6049/udp"
    restart: always
  IOT-V2-Emqx:
    image: emqx/emqx:latest
    container_name: emqx
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8883:8883"
      - "8084:8084"
      - "18083:18083"
    restart: always
  IOT-v2-Mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'devices'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - "20306:3306"