Mode: debug
ProgramName: ""
BaseURL: ""
Author: ""
Listen: "0.0.0.0"
Port: "8001"
SKLMysql:
    Host: "localhost"
    Port: "20306"
    User: "user"
    Pass: "password"
    Database: "devices"
    Debug: false
    Trace: false
TDEngine:
    Host: "localhost"
    Port: "6041"
    User: "root"
    Pass: "taosdata"
    Database: "power"
    DriverName: "taosRestful"



